### ISSUE TITLE
[NBS] Fresh devices should be synced first

### ISSUE THREAD

**Issue by drbasic** [ydb-platform/nbs#1067]
Если часть устройств диска помечены как "warning", а часть как "fresh", то чтобы снизить риск потери данных, первыми должны наливаться именно fresh устройства. Сейчас же первыми наливаются "warning" устройства.

Заодно сделать чтобы в табличке мониторинговой страницы disk-registry отображалось что у диска наливается fresh девайс.

**Comment by qkrorlqr** [comment]
Достаточно просто поменять приоритеты тут: https://github.com/ydb-platform/nbs/blob/36c172ff0df3593d0ee49982f3c624c47984b157/cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp#L69
Сейчас там сначала ищутся миграции - нужно сначала искать, а не надо ли что-то реплицировать, и только если не надо, тогда уже к миграциям переходить.

**Comment by drbasic** [comment]
https://github.com/ydb-platform/nbs/pull/1334

**Comment by drbasic** [comment]
https://github.com/ydb-platform/nbs/pull/1348
