### ISSUE TITLE
[NBS] Losing local disks metrics after nbs restart 

### ISSUE THREAD

**Issue by komarevtsev-d** [ydb-platform/nbs#1242]
There is a rare issue with metrics delivery to NBS from the vhost-server, which can occur after the restart of the NBS service. For some reason, [ReadStatsImpl](https://github.com/ydb-platform/nbs/blob/69d12574c03d23735a8f5f56d5abc6b3a660438d/cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp#L304) loop doesn't send `SIGUSR1` signal. And there were no logs with `Read stats error...`, so the loop didn't exit by error.
System calls tracing with `sudo strace -p <nbs_pid> -e kill -f -tt` showed that the NBS was sending signals to only one of the two vhost-server processes.
Other than that, the two disks were working just fine.

**Comment by komarevtsev-d** [comment]
CC @budevg

**Comment by drbasic** [comment]
Проблема в ненадежности всей конструкции.
https://github.com/ydb-platform/nbs/blame/main/cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp#L298
Если Дочерний процесс не обработает SIGUSR1, то он не пришлет ответ и весь этот бесконечный цикл повиснет на ожидании данных. 
Для этого достаточно в дочернем процессе не успеть подготовиться к приему сигналов и сигнал будет пропущен.
