### ISSUE TITLE
[NBS] Добавить Disk Registry Tablet Id в конфиг

### ISSUE THREAD

**Issue by EvgeniyKozev** [ydb-platform/nbs#1267]
При рестарте DA нам нужно: пойти в DR_proxy, который идет в HIVE_proxy для того, что бы получить DR Tablet ID.
Проблема в том, что HIVE может быть не доступен какое то время.
![image](https://github.com/ydb-platform/nbs/assets/127485837/82c1688d-890f-4334-a1a8-9290fa3170c4)
На скрине (ElapsedMicrosecByActivity) видно, что HIVE переезжал (по какой причине не понятно) и пока поднимался, был не сильно доступен.

Как вариант решения проблемы предлагается добавить в коинфиг ID таблетки DR т.к. он не меняется.

В таком случае, при необходимости мы берем ID из конфига, а в случаи проблем с конфигом или полученным ID из него, идем по старой схеме.

**Comment by EvgeniyKozev** [comment]
@komarevtsev-d Даня, можешь добавить информации о том, почему конект не случился, после того, как хайв ожил

**Comment by komarevtsev-d** [comment]
> @komarevtsev-d Даня, можешь добавить информации о том, почему конект не случился, после того, как хайв ожил

https://github.com/ydb-platform/nbs/pull/1279/files#r1616124812
