### ISSUE TITLE
[DM] Implement GetChangedBlocks for checkpoint with shadow disk

### ISSUE THREAD

**Issue by drbasic** [ydb-platform/nbs#1297]
Нужно начать использовать GetChangedBlocks для NRD дисков. 
Если NBS не умеет отвечать на GetChangedBlocks или фича про теневые диски выключена, то NBS вернет ошибку E_ARGUMENT и текст типа "Disk registry based disks can not handle GetChangedBlocks requests for normal checkpoints, DiskId:"
https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp#L895

Т.е. нужно сделать запрос, и если получен E_ARGUMENT, то действовать как сейчас - считая что все блоки изменялись и их нужно сохранить в снэпшот.
NBS сделано в https://github.com/ydb-platform/nbs/issues/1241
https://github.com/ydb-platform/nbs/pull/1245

Ожидается что имя чекпоинта передается через параметр HighCheckpointId

**Comment by SvartMetal** [comment]
Здесь логичнее было бы добавить код ошибки E_NOT_SUPPORTED, так как:
* парсить код ошибки это хрупко
* выглядит как костыль

**Comment by drbasic** [comment]
Я поменяю на E_NOT_SUPPORTED
но если в коде DM не проверить E_ARGUMENT то катить DM рядом со старыми NBS не получится.

**Comment by SvartMetal** [comment]
> Я поменяю на E_NOT_SUPPORTED
но если в коде DM не проверить E_ARGUMENT то катить DM рядом со старыми NBS не получится.

Так всё-таки, почему не отключать фичу на уровне Snapshot? Его ведь проще прокатить чем NBS

**Comment by drbasic** [comment]
Не понимаю о чем ты. 
1. Снэпшотилка при чтении данных из чекпоинта может спрашивать какие блоки пустые через GetChangedBlocks
2. Раньше для diskregistry-based дисков это функция была реализвана через заглушку и всегда возвращала ошибку E_ARGUMENT
3. на стороне снэпшотилки для таких дисков функция просто не вызывается
4. сейчас для дисков с теневыми дисками GetChangedBlocks работает

Предлагается сделать:
1. начать использовать GetChangedBlocks для NRD дисков.
2. если получен E_ARGUMENT, то действовать как сейчас, не вызывать дальше GetChangedBlocks потому что это бесполезно по двум причинам: либо это старый NBS, который не поддерживает GetChangedBlocks, либо чекпоинт делается без теневого диска.

Ты предложил заменить код возврата E_ARGUMENT на E_NOT_SUPPORTED, что ок, я сделаю это. Но пока предлагаю на стороне снэпшотилки реализовать логику, что описана выше и одинаково обрабатывать как E_ARGUMENT так и E_NOT_SUPPORTED, чтобы гарантированно работать со всеми версиями NBS. 
В будущем же, после раскатки новой версии NBS, которая отвечает E_NOT_SUPPORTED оторвать проверку E_ARGUMENT.

**Comment by drbasic** [comment]
Изменения на стороне  NBS https://github.com/ydb-platform/nbs/pull/1387/files
На стороне  DM https://github.com/ydb-platform/nbs/pull/1329

**Comment by SvartMetal** [comment]
Ты прекрасно понимаешь о чём я. 
Эту фичу проще включать/отключать на стороне Snapshot, потому что кол-во хостов Snapshot сильно меньше чем кол-во хостов NBS.
Но я в целом не против отключать фичу на стороне NBS и добавить обработку E_NOT_IMPLEMENTED на стороне Snapshot

**Comment by drbasic** [comment]
На стороне NBS каких-то настроек не предусмотрено. NBS  если может обрабатывать запросы GetChangedBlocks, то возвращает список блоков, либо отвечает E_NOT_IMPLEMENTED.
А на стороне Snapshot действительно происходит решение будем мы пользоваться GetChangedBlocks или нет.
