### ISSUE TITLE
[NBS] GRPC disk info handle 

### ISSUE THREAD

**Issue by LugarkPirog** [ydb-platform/nbs#1320]
It would be useful to have a possibility to export information about the disks that are in use and registered in NBS. The info that handle should provide is approximately as follows:

- disk_id/name, 
- disk_serial_id, - if exists
- server_fqdn,
- disk_total_space_gb,
- disk_used_space_gb

**Comment by antonmyagkov** [comment]
Implemented in main and stable-23-3

QueryAgentsInfo command implemented in blockstoreclient. It returns disks summary for each agent.

you can find protobuf response format for QueryAgentsInfo here: https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/public/api/protos/disk.proto#L169-L224
