### ISSUE TITLE
[NBS] Remove used blocks bitmap for encrypted NRD

### ISSUE THREAD

**Issue by drbasic** [ydb-platform/nbs#1376]
Сейчас для определения факта зашифрован блок или нет используется карта, которая обновляется при записи блока.
Можно действовать проще, проверять прочитанный блок, если он содержит все нули - то отдавать его клиенту не расшифровывая. Это упростит логику и избавит от походов в локальную базу.
Для дисков которые уже имеют такую карту ничего страшного не произойдет - карта просто перестанет использоваться.

**Comment by qkrorlqr** [comment]
Это на самом деле часть https://github.com/ydb-platform/nbs/issues/176 - там написано ровно это (только еще написано про проверку нулей при записи и написано, что при чтении можно проверять не весь блок, а только, например, первые 128 байт)
