### ISSUE TITLE
[NBS] Support online resize for PVCs mounted in Filesystem mode

### ISSUE THREAD

**Issue by PhantomPhreak** [ydb-platform/nbs#1657]
We need NBS disks mounted in `Filesystem` mode via CSI to support online resize **up** (`allowVolumeExpansion` storageclass feature), in order to provide our services a possibility to scale up underlying storage by a client's request.
Please help to implement it.

Many thanks!

**Comment by orloffv** [comment]
If it could be downsized it would be great for us (another team)

**Comment by PhantomPhreak** [comment]
@orloffv Downsize is kinda tricky operation, there are many things that could go wrong. I think it would be better to request/implement via separated feature request

**Comment by antonmyagkov** [comment]
https://kubernetes-csi.github.io/docs/volume-expansion.html

**Comment by antonmyagkov** [comment]
We need to isolated e2e test for resize device command to test resize independently from csi driver.
Discussion: [issue-1657: resize nbd device by antonmyagkov · Pull Request #1830 · ydb-platform/nbs](https://github.com/ydb-platform/nbs/pull/1830#discussion_r1728596883)

**Comment by antonmyagkov** [comment]
We need to do some refactoring: https://github.com/ydb-platform/nbs/pull/1748#discussion_r1743430963
