### ISSUE TITLE
[NBS] Полноценные снимки с NRD

### ISSUE THREAD

**Issue by drbasic** [ydb-platform/nbs#2]
Общая идея такая:

Добавляем еще одну реплику к существующему диску, так если это был mirror3 он станет mirror4.
Существующей машинерией наливаем эту новую реплику
Когда реплика будет налита, отключаем ее, переводим в состояние readonly
ассоццируем созданную рекплику с чекпоинтом
говорим что создали чекпоинт
все чтения из чекпоинта перенаправляем в реплику
при удаления данных чекпоинта или самого чекпоинта удаляем эту дополнительную реплику
если в процессе наливки у нас ломается девайс под репликой - мы заменяем его на новый и продолжает наливать реплику, тут должна работать уже существующая машинерия.
если после наливки реплики у нее ломается девайс, то мы отдаем ошибку чтения. Диск менджер в таком случае должен удалить чекпоинт и начать все с начала.

**Comment by EvgeniyKozev** [comment]
Тестовый коммент в существующей задаче

**Comment by EvgeniyKozev** [comment]
Тестовый комментарий 2

**Comment by BarkovBG** [comment]
https://github.com/ydb-platform/nbs/issues/1461
