### ISSUE TITLE
[NBS] NonreplicatedPartitionRdmaActor implementation lacks volume mode and checkpoint checks

### ISSUE THREAD

**Issue by budevg** [ydb-platform/nbs#216]
When processing read/write request the `NonreplicatedPartitionActor` checks for volume mode (is read only/ has broken device) and whether checkpoint support is needed.
https://github.com/ydb-platform/nbs/blob/f0bfcb041e1d1c01ced1edd994832656d0974aa8/cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp#L140

This functionality is missing from `NonreplicatedPartitionRdmaActor`

**Comment by qkrorlqr** [comment]
checkpoint checks are implemented at the volume level: https://github.com/ydb-platform/nbs/blob/4320a453409b4d97922839017b91a969fa1baebe/cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp#L682

seems that we need to fix only the volume mode check

**Comment by tpashkin** [comment]
@budevg do we need to do anything else regarding this issue?

**Comment by budevg** [comment]
No everything was done in #559 ... closing the issue
