### ISSUE TITLE
[Blockstore] CSI driver should support read-only access mode

### ISSUE THREAD

**Issue by SvartMetal** [ydb-platform/nbs#2285]
Here we have read-write access mode hardcoded https://github.com/ydb-platform/nbs/blob/116fa80a741a5f1b59155aadf799dd130a56e98d/cloud/blockstore/tools/csi_driver/internal/driver/node.go#L490

**Comment by antonmyagkov** [comment]
Publishing readonly volumes fails if volume mount group parameter is provided

fix: https://github.com/ydb-platform/nbs/pull/2443
