### ISSUE TITLE
[Filestore] Make Filestore read throughput scalable with respect to the number of clients

### ISSUE THREAD

**Issue by qkrorlqr** [ydb-platform/nbs#324]
We want a single FS to be able to provide more read throughput when more clients (VMs) connect to the FS. The idea is simple: right now the bottleneck for large reads is the IndexTablet, because all data is proxied via it. But we don't really need to transfer all data via the tablet. The tablet can return <BSGroupId, BlobId, ByteRange> tupes to the client (filestore-vhost) instead of returning the requested data. The client can read the data from the specified BSGroups by itself. A fallback should be implemented for the case when the client cannot read the data by itself - e.g. if the specified BlobId has already been deleted or if the client has no direct access to the storage nodes.

**Comment by qkrorlqr** [comment]
Включать фичу per fs будем как-то так:
`filestore-client executeaction --action changestorageconfig --input-json '{"FileSystemId": "cah4f26mi30sd875be4r", "StorageConfig": {"TwoStageReadEnabled": true}}'`

**Comment by qkrorlqr** [comment]
![Screenshot from 2024-02-19 22-02-36](https://github.com/ydb-platform/nbs/assets/1497699/db78a8a3-0caf-433a-a40e-abe3d308a15e)
managed to scale read throughput to 10 GB/s total for 10 VMs

**Comment by debnatkh** [comment]
After optimizations in `IndexTablet` managed to get 13-15 GB/s for 10 vms.

![image](https://github.com/ydb-platform/nbs/assets/16041594/3d6cf8d2-0c6e-4515-a620-679f2d2fbf17)

**Comment by qkrorlqr** [comment]
Implemented, deployed, works well, closing the issue

**Comment by debnatkh** [comment]
20 clients, fio, num_jobs = 32, bs = 1M

~25-30 GB/s

<img width="1232" alt="image" src="https://github.com/ydb-platform/nbs/assets/16041594/543cc726-c323-4c9c-935a-0a96488b9616">
