### ISSUE TITLE
Always adjust blocks count on the device 

### ISSUE THREAD

**Issue by komarevtsev-d** [ydb-platform/nbs#338]
[This](https://github.com/ydb-platform/nbs/blob/688d3cfb59d4fdb97536c316d255faf98bbbc649/cloud/blockstore/libs/storage/disk_registry/model/agent_list.cpp#L252) condition may result in a loss of the blocks count on the device. We probably should just get rid of it.

**Comment by qkrorlqr** [comment]
@sharpeye
