### ISSUE TITLE
[Disk Manager] failures of disk relocation tests

### ISSUE THREAD

**Issue by BarkovBG** [ydb-platform/nbs#491]

**Comment by BarkovBG** [comment]
list of failing tests:

- TestDiskServiceMigrateEmptyOverlayDiskWithoutAliveSrcImage 
- TestDiskServiceMigrateOverlayDiskInParallelWithDifferentDstZoneIDs (https://github.com/ydb-platform/nbs/actions/runs/7933975101)
- TestDiskServiceMigrateHddNonreplDisk (https://github.com/ydb-platform/nbs/actions/runs/7933986575)

**Comment by BarkovBG** [comment]
status for TestDiskServiceMigrateEmptyOverlayDiskWithoutAliveSrcImage:
- https://github.com/ydb-platform/nbs/pull/485

**Comment by BarkovBG** [comment]
status for TestDiskServiceMigrateOverlayDiskInParallelWithDifferentDstZoneIDs:
- diagnostics

**Comment by BarkovBG** [comment]
status for TestDiskServiceMigrateHddNonreplDisk:
- need to catch the problem locally

**Comment by SvartMetal** [comment]
Reproduced in tests http://ci.nbs.nemax-sandbox.nebiuscloud.net:8080/ci/logs/run_24_04_28__13/cloud/disk_manager/internal/pkg/facade/disk_service_nemesis_test/test-results/disk_service_nemesis_test/chunk3/testing_out_stuff/

**Comment by BarkovBG** [comment]
> Reproduced in tests http://ci.nbs.nemax-sandbox.nebiuscloud.net:8080/ci/logs/run_24_04_28__13/cloud/disk_manager/internal/pkg/facade/disk_service_nemesis_test/test-results/disk_service_nemesis_test/chunk3/testing_out_stuff/

new issue https://github.com/ydb-platform/nbs/issues/1097
