### ISSUE TITLE
[Filestore] Change compaction policy inside IndexTablet

### ISSUE THREAD

**Issue by NewBediver** [ydb-platform/nbs#688]
There is reason to believe that lack of policy leads to peaks in memory consumption.
![image](https://github.com/ydb-platform/nbs/assets/51848889/2ba27cfe-3e1a-4c45-b727-d6b752ca2145)

You can take the blockstore policy as the default:
https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/storage/core/tablet_schema.cpp#L11

Important notes:
- The number of levels can only be increased, if you try to decrease it, there will be a drop in verify (I tried doing a rollback to the default policy in testing and I didn't have verify, everything worked properly. It's worth repeating the experiment again).
- If there are two versions of code that apply different policies, you should make sure that on version rollback there is no attempt to decrease.

Features config was implemented earlier for filestore, so we can try enabling the new compaction policy for new tablets, and leave all the old ones on the old policy via features-config. So now the following is left to do:
- [ ] Add compaction-policy feature in nfs-features.txt and add there all existing filesystems.
- [ ] Roll out a new release with compaction-policy enabled (you can use the PR as a basis: https://github.com/ydb-platform/nbs/pull/431 ).
- [ ] After a few weeks enable the feature for all filesystems (remove the list from nfs-features.txt).

**Comment by qkrorlqr** [comment]
> There is reason to believe that lack of policy leads to peaks in memory consumption.

It's not the main problem. Bad compaction policy causes terrible commit latency. If we take a look at the traces of our write requests, we will see that we spend the majority of the time waiting for tx commit. Some really bad examples:
`
     0.000     +0.000 ms [178968472664894] FILESTORE_STORAGE_PROVIDER.RequestReceived_Tablet(requestType='WriteData', requestId='15045314', fsId='', mediaKind='1')
     0.012     +0.012 ms [178968472689838] FILESTORE_STORAGE_PROVIDER.RequestAdvanced_Tablet(requestType='WriteData', requestId='15045314')
     0.016     +0.004 ms [178968472698520] FILESTORE_STORAGE_PROVIDER.TxInit(name='WriteData', requestId='15045314')
     0.018     +0.002 ms [178968472702362] LWTRACE_INTERNAL_PROVIDER.Fork(spanId='958')
     0.018     +0.001 ms [178968472703436] FILESTORE_STORAGE_PROVIDER.ForkFailed(name='WriteData', requestId='15045314')
     0.028     +0.009 ms [178968472722746] FILESTORE_STORAGE_PROVIDER.TxPrepare(name='WriteData', requestId='15045314')
     0.060     +0.033 ms [178968472791170] FILESTORE_STORAGE_PROVIDER.TxExecute(name='WriteData', requestId='15045314')
     1.182     +1.122 ms [178968475140874] FILESTORE_STORAGE_PROVIDER.TxExecuteDone(name='WriteData', requestId='15045314')
    75.429    +74.247 ms [178968630694724] FILESTORE_STORAGE_PROVIDER.TxComplete(name='WriteData', requestId='15045314')
    75.434     +0.005 ms [178968630704892] FILESTORE_STORAGE_PROVIDER.ResponseSent_Tablet(requestType='WriteData', requestId='15045314')
`
`
     0.000     +0.000 ms [178968700265354] FILESTORE_STORAGE_PROVIDER.RequestReceived_Tablet(requestType='WriteData', requestId='15045322', fsId='', mediaKind='1')
     0.012     +0.012 ms [178968700291086] FILESTORE_STORAGE_PROVIDER.RequestAdvanced_Tablet(requestType='WriteData', requestId='15045322')
     0.016     +0.003 ms [178968700298244] FILESTORE_STORAGE_PROVIDER.TxInit(name='WriteData', requestId='15045322')
     0.017     +0.002 ms [178968700301576] LWTRACE_INTERNAL_PROVIDER.Fork(spanId='954')
     0.018     +0.001 ms [178968700302996] FILESTORE_STORAGE_PROVIDER.ForkFailed(name='WriteData', requestId='15045322')
     0.024     +0.006 ms [178968700315690] FILESTORE_STORAGE_PROVIDER.TxPrepare(name='WriteData', requestId='15045322')
     0.065     +0.041 ms [178968700401138] FILESTORE_STORAGE_PROVIDER.TxExecute(name='WriteData', requestId='15045322')
     1.581     +1.517 ms [178968703578636] FILESTORE_STORAGE_PROVIDER.TxExecuteDone(name='WriteData', requestId='15045322')
    33.035    +31.453 ms [178968769475580] FILESTORE_STORAGE_PROVIDER.TxComplete(name='WriteData', requestId='15045322')
    33.040     +0.005 ms [178968769486428] FILESTORE_STORAGE_PROVIDER.ResponseSent_Tablet(requestType='WriteData', requestId='15045322')
`

A "normal" case - still really bad but not as bad:
`
     0.000     +0.000 ms [178969952275276] FILESTORE_STORAGE_PROVIDER.RequestReceived_Tablet(requestType='WriteData', requestId='15045400', fsId='', mediaKind='1')
     0.013     +0.013 ms [178969952302088] FILESTORE_STORAGE_PROVIDER.RequestAdvanced_Tablet(requestType='WriteData', requestId='15045400')
     0.017     +0.004 ms [178969952309890] FILESTORE_STORAGE_PROVIDER.TxInit(name='WriteData', requestId='15045400')
     0.018     +0.002 ms [178969952313270] LWTRACE_INTERNAL_PROVIDER.Fork(spanId='917')
     0.019     +0.001 ms [178969952314332] FILESTORE_STORAGE_PROVIDER.ForkFailed(name='WriteData', requestId='15045400')
     0.023     +0.005 ms [178969952323790] FILESTORE_STORAGE_PROVIDER.TxPrepare(name='WriteData', requestId='15045400')
     0.049     +0.026 ms [178969952378132] FILESTORE_STORAGE_PROVIDER.TxExecute(name='WriteData', requestId='15045400')
     1.270     +1.220 ms [178969954935020] FILESTORE_STORAGE_PROVIDER.TxExecuteDone(name='WriteData', requestId='15045400')
     7.797     +6.527 ms [178969968609760] FILESTORE_STORAGE_PROVIDER.TxComplete(name='WriteData', requestId='15045400')
     7.801     +0.005 ms [178969968619578] FILESTORE_STORAGE_PROVIDER.ResponseSent_Tablet(requestType='WriteData', requestId='15045400')
`

Happens all the time

**Comment by debnatkh** [comment]
![image](https://github.com/ydb-platform/nbs/assets/16041594/8a95c941-a810-46af-8ca2-fe22ed627739)

We have successfully enabled the `NewLocalDBCompactionPolicyEnabled` flag.

The chart above is for the sensor `{service="tablets", host="cluster", queue="queue_compaction_gen*", sensor="InFlyTasks", database="total"}`. The background compaction operations have drastically decreased. This had virtually no effect on the performance.
