### ISSUE TITLE
[Disk Manager] add tests for "incremental" table 

### ISSUE THREAD

**Issue by BarkovBG** [ydb-platform/nbs#741]
@leftmain has the details

**Comment by leftmain** [comment]
there's no tests for incremental table in DM (only general logic like here https://github.com/ydb-platform/nbs/blob/4775546bac548f5931bb42f9d2f356f19c1cc12b/cloud/disk_manager/internal/pkg/resources/snapshots_test.go)

**Comment by BarkovBG** [comment]
сделано в рамках https://github.com/ydb-platform/nbs/issues/1636 

в пре https://github.com/ydb-platform/nbs/pull/1980
