### ISSUE TITLE
[NBS] Durable client takes a long time to retry pending requests on disk agent restart

### ISSUE THREAD

**Issue by komarevtsev-d** [ydb-platform/nbs#885]
When restart of a disk agent takes more than couple of seconds, io requests will be slowed down by 10-20 seconds. The theory is that our backoff policy sets unreasonable timeouts.

**Comment by qkrorlqr** [comment]
> When restart of a disk agent takes more than couple of seconds, io requests will be slowed down by 10-20 seconds. The theory is that our backoff policy sets unreasonable timeouts.

но durable-клиент же вроде ни при чем - проблема же в большом времени между ретраями RegisterAgent-запроса от агента в DR Proxy?

**Comment by komarevtsev-d** [comment]
> > When restart of a disk agent takes more than couple of seconds, io requests will be slowed down by 10-20 seconds. The theory is that our backoff policy sets unreasonable timeouts.
> 
> но durable-клиент же вроде ни при чем - проблема же в большом времени между ретраями RegisterAgent-запроса от агента в DR Proxy?

Не, это не основная причина. Я открою в ближайшее время ПР с фиксом таймаутов запросов.
