### ISSUE TITLE
[NBS] Spawn vhost-server as a child for nbsd

### ISSUE THREAD

**Issue by komarevtsev-d** [ydb-platform/nbs#962]
When nbsd is restarted, all vhost-server processes should be killed as well. As of now, systemd is resposible for the killing. 
We should mark vhost as a child somewhere [here](https://github.com/ydb-platform/nbs/blob/69d12574c03d23735a8f5f56d5abc6b3a660438d/cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp#L157).

**Comment by komarevtsev-d** [comment]
JFYI @sharpeye @budevg

**Comment by qkrorlqr** [comment]
А зачем тут что-то менять?

**Comment by komarevtsev-d** [comment]
> А зачем тут что-то менять?

Есть гипотеза, что с переходом на cgroups v2 systemd перестанет убивать vhost-server
